name: permission_plus_android
description: "Android implementation of the permission_plus plugin."

version: 0.0.2

homepage: https://github.com/jagadeeshchoudhary/permission_plus_android
repository: https://github.com/jagadeeshchoudhary/permission_plus_android/tree/main
issue_tracker: https://github.com/jagadeeshchoudhary/permission_plus_android/issues

environment:
  sdk: ^3.12.0
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.18.0
  permission_plus_platform_interface: ^0.1.0
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  pigeon: ^26.3.4

flutter:
  plugin:
    platforms:
      android:
        package: com.jagadeeshchoudhary.permission_plus_android
        pluginClass: PermissionPlusAndroidPlugin

topics:
  - permissions
  - android
