// Autogenerated from Pigeon (v26.3.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package com.jagadeeshchoudhary.permission_plus_android

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object PermissionPlusApiPigeonUtils {

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun doubleEquals(a: Double, b: Double): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0) 0.0 else a) == (if (b == 0.0) 0.0 else b) || (a.isNaN() && b.isNaN())
  }

  fun floatEquals(a: Float, b: Float): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0f) 0.0f else a) == (if (b == 0.0f) 0.0f else b) || (a.isNaN() && b.isNaN())
  }

  fun doubleHash(d: Double): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (d == 0.0) 0.0 else d
    val bits = java.lang.Double.doubleToLongBits(normalized)
    return (bits xor (bits ushr 32)).toInt()
  }

  fun floatHash(f: Float): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (f == 0.0f) 0.0f else f
    return java.lang.Float.floatToIntBits(normalized)
  }

  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a === b) {
      return true
    }
    if (a == null || b == null) {
      return false
    }
    if (a is ByteArray && b is ByteArray) {
      return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
      return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
      return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!doubleEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is FloatArray && b is FloatArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!floatEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is Array<*> && b is Array<*>) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!deepEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is List<*> && b is List<*>) {
      if (a.size != b.size) return false
      val iterA = a.iterator()
      val iterB = b.iterator()
      while (iterA.hasNext() && iterB.hasNext()) {
        if (!deepEquals(iterA.next(), iterB.next())) return false
      }
      return true
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      if (a.size != b.size) return false
      for (entry in a) {
        val key = entry.key
        var found = false
        for (bEntry in b) {
          if (deepEquals(key, bEntry.key)) {
            if (deepEquals(entry.value, bEntry.value)) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if (!found) return false
      }
      return true
    }
    if (a is Double && b is Double) {
      return doubleEquals(a, b)
    }
    if (a is Float && b is Float) {
      return floatEquals(a, b)
    }
    return a == b
  }

  fun deepHash(value: Any?): Int {
    return when (value) {
      null -> 0
      is ByteArray -> value.contentHashCode()
      is IntArray -> value.contentHashCode()
      is LongArray -> value.contentHashCode()
      is DoubleArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + doubleHash(item)
        }
        result
      }
      is FloatArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + floatHash(item)
        }
        result
      }
      is Array<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is List<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is Map<*, *> -> {
        var result = 0
        for (entry in value) {
          result += ((deepHash(entry.key) * 31) xor deepHash(entry.value))
        }
        result
      }
      is Double -> doubleHash(value)
      is Float -> floatHash(value)
      else -> value.hashCode()
    }
  }

}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : RuntimeException()

/** Mirror of `PermissionType` from `permission_plus_platform_interface`. */
enum class PermissionTypeMessage(val raw: Int) {
  CAMERA(0),
  MICROPHONE(1),
  PHOTOS(2),
  PHOTOS_ADD_ONLY(3),
  LOCATION(4),
  LOCATION_ALWAYS(5),
  LOCATION_WHEN_IN_USE(6),
  NOTIFICATION(7),
  CONTACTS(8),
  CONTACTS_READ_ONLY(9),
  CONTACTS_WRITE_ONLY(10),
  CALENDAR(11),
  CALENDAR_READ_ONLY(12),
  CALENDAR_WRITE_ONLY(13),
  REMINDERS(14),
  STORAGE(15),
  STORAGE_READ_ONLY(16),
  STORAGE_WRITE_ONLY(17),
  BLUETOOTH(18),
  SPEECH(19),
  MEDIA_LIBRARY(20),
  SENSORS(21),
  PHONE(22),
  SMS(23),
  APP_TRACKING_TRANSPARENCY(24),
  CRITICAL_ALERTS(25),
  VIDEOS(26),
  AUDIO(27);

  companion object {
    fun ofRaw(raw: Int): PermissionTypeMessage? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/** Mirror of `PermissionStatus` from `permission_plus_platform_interface`. */
enum class PermissionStatusMessage(val raw: Int) {
  NOT_DETERMINED(0),
  GRANTED(1),
  DENIED(2),
  PERMANENTLY_DENIED(3),
  RESTRICTED(4),
  LIMITED(5),
  PROVISIONAL(6);

  companion object {
    fun ofRaw(raw: Int): PermissionStatusMessage? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/** Mirror of `LocationAccuracy` from `permission_plus_platform_interface`. */
enum class LocationAccuracyMessage(val raw: Int) {
  REDUCED(0),
  PRECISE(1);

  companion object {
    fun ofRaw(raw: Int): LocationAccuracyMessage? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/**
 * Represents a single entry in a permission → status map.
 *
 * Used for returning results from [requestPermissions], since Pigeon
 * does not support `Map` with enum keys directly.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class PermissionStatusMapEntry (
  val permission: PermissionTypeMessage,
  val status: PermissionStatusMessage
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): PermissionStatusMapEntry {
      val permission = pigeonVar_list[0] as PermissionTypeMessage
      val status = pigeonVar_list[1] as PermissionStatusMessage
      return PermissionStatusMapEntry(permission, status)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      permission,
      status,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as PermissionStatusMapEntry
    return PermissionPlusApiPigeonUtils.deepEquals(this.permission, other.permission) && PermissionPlusApiPigeonUtils.deepEquals(this.status, other.status)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + PermissionPlusApiPigeonUtils.deepHash(this.permission)
    result = 31 * result + PermissionPlusApiPigeonUtils.deepHash(this.status)
    return result
  }
}
private open class PermissionPlusApiPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          PermissionTypeMessage.ofRaw(it.toInt())
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          PermissionStatusMessage.ofRaw(it.toInt())
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          LocationAccuracyMessage.ofRaw(it.toInt())
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          PermissionStatusMapEntry.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is PermissionTypeMessage -> {
        stream.write(129)
        writeValue(stream, value.raw.toLong())
      }
      is PermissionStatusMessage -> {
        stream.write(130)
        writeValue(stream, value.raw.toLong())
      }
      is LocationAccuracyMessage -> {
        stream.write(131)
        writeValue(stream, value.raw.toLong())
      }
      is PermissionStatusMapEntry -> {
        stream.write(132)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}


/**
 * Host API implemented in Kotlin, called from Dart.
 *
 * Generated interface from Pigeon that represents a handler of messages from Flutter.
 */
interface PermissionPlusHostApi {
  /** Checks the current status of [permission] without triggering a request. */
  fun checkPermission(permission: PermissionTypeMessage, callback: (Result<PermissionStatusMessage>) -> Unit)
  /** Requests [permission] from the user. */
  fun requestPermission(permission: PermissionTypeMessage, callback: (Result<PermissionStatusMessage>) -> Unit)
  /** Requests multiple [permissions] at once. */
  fun requestPermissions(permissions: List<PermissionTypeMessage>, callback: (Result<List<PermissionStatusMapEntry>>) -> Unit)
  /** Opens the platform's app settings page. */
  fun openSettings(callback: (Result<Boolean>) -> Unit)
  /**
   * Whether the platform recommends showing a rationale before requesting
   * [permission].
   */
  fun shouldShowRationale(permission: PermissionTypeMessage, callback: (Result<Boolean>) -> Unit)
  /** Gets the current location accuracy level. */
  fun getLocationAccuracy(callback: (Result<LocationAccuracyMessage>) -> Unit)
  /**
   * Requests temporary precise location access.
   *
   * On Android this returns the current location permission status.
   */
  fun requestTemporaryPreciseLocation(purposeKey: String, callback: (Result<PermissionStatusMessage>) -> Unit)

  companion object {
    /** The codec used by PermissionPlusHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      PermissionPlusApiPigeonCodec()
    }
    /** Sets up an instance of `PermissionPlusHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: PermissionPlusHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.permission_plus_android.PermissionPlusHostApi.checkPermission$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val permissionArg = args[0] as PermissionTypeMessage
            api.checkPermission(permissionArg) { result: Result<PermissionStatusMessage> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(PermissionPlusApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(PermissionPlusApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.permission_plus_android.PermissionPlusHostApi.requestPermission$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val permissionArg = args[0] as PermissionTypeMessage
            api.requestPermission(permissionArg) { result: Result<PermissionStatusMessage> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(PermissionPlusApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(PermissionPlusApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.permission_plus_android.PermissionPlusHostApi.requestPermissions$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val permissionsArg = args[0] as List<PermissionTypeMessage>
            api.requestPermissions(permissionsArg) { result: Result<List<PermissionStatusMapEntry>> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(PermissionPlusApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(PermissionPlusApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.permission_plus_android.PermissionPlusHostApi.openSettings$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.openSettings{ result: Result<Boolean> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(PermissionPlusApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(PermissionPlusApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.permission_plus_android.PermissionPlusHostApi.shouldShowRationale$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val permissionArg = args[0] as PermissionTypeMessage
            api.shouldShowRationale(permissionArg) { result: Result<Boolean> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(PermissionPlusApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(PermissionPlusApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.permission_plus_android.PermissionPlusHostApi.getLocationAccuracy$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.getLocationAccuracy{ result: Result<LocationAccuracyMessage> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(PermissionPlusApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(PermissionPlusApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.permission_plus_android.PermissionPlusHostApi.requestTemporaryPreciseLocation$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val purposeKeyArg = args[0] as String
            api.requestTemporaryPreciseLocation(purposeKeyArg) { result: Result<PermissionStatusMessage> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(PermissionPlusApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(PermissionPlusApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
